services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/web
      - .env/development/database
#  database:
#    image: postgres
#    env_file:
#      - .env/development/database
#    volumes:
#      - db_data:/var/lib/postgresql/data

volumes:
#  db_data:
  gem_cache: