FROM ruby:3.1.2

LABEL maintainer="cayala.w@gmail.com"

#Allow ap tot work with https-based sources
RUN apt-get update -yqq && \
    apt-get install -yqq --no-install-recommends apt-transport-https

# Install packages
RUN apt-get update -yqq && \
    apt-get install -yqq --no-install-recommends nodejs sqlite3

COPY Gemfile* /usr/src/app/
WORKDIR /usr/src/app
ENV BUNDLE_PATH /gems
RUN bundle install

COPY . /usr/src/app/

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["bin/rails", "s", "-b", "0.0.0.0"]